CREATE TABLE Product (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    number_in_stock INT NOT NULL,
    image_urls JSON DEFAULT NULL,
    add_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    width DOUBLE PRECISION DEFAULT NULL,
    height DOUBLE PRECISION DEFAULT NULL,
    length DOUBLE PRECISION DEFAULT NULL,
    weight DOUBLE PRECISION DEFAULT NULL,
    material VARCHAR(255) DEFAULT NULL,
    color VARCHAR(255) DEFAULT NULL,
    price DOUBLE PRECISION DEFAULT NULL,
    hidden BOOLEAN NOT NULL DEFAULT false,
    discount DOUBLE PRECISION NOT NULL DEFAULT 100,
    sku VARCHAR(255) NOT NULL DEFAULT 'UNKNOWN',
    attributes JSONB DEFAULT '{}',
    version INT NOT NULL DEFAULT 1,
    currency_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Product
ADD CONSTRAINT fk_product_currency FOREIGN KEY (currency_id) REFERENCES Currency (id) ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE INDEX idx_product_sku ON Product (sku);