CREATE TABLE shop_info (
    id SERIAL PRIMARY KEY,
    eshop_name VARCHAR(255),
    address VARCHAR(255),
    telephone VARCHAR(50),
    email VARCHAR(100),
    about_us TEXT,
    how_to_order TEXT,
    business_conditions TEXT,
    privacy_policy TEXT,
    shipping_info TEXT,
    payment TEXT,
    refund TEXT,
    color_code VARCHAR(20),
    logo VARCHAR(255),
    carousel_pictures JSON,
    company_name VARCHAR(255),
    cin VARCHAR(50)
);

INSERT INTO shop_info (
    eshop_name,
    address,
    telephone,
    email,
    about_us,
    how_to_order,
    business_conditions,
    privacy_policy,
    shipping_info,
    payment,
    refund,
    color_code,
    logo,
    carousel_pictures,
    company_name,
    cin
) VALUES (
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '[]',
    '',
    ''
);