controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
product_edit:
    path: '/product_edit/{id}'
    controller: App\Controller\ProductController::edit
save_product:
    path: '/product_save/{id}'
    controller: App\Controller\ProductController::saveProduct
save_image:
    path: '/image_save/'
    controller: App\Controller\ProductController::saveImage
register_employee:
    path: 'register_employee'
    controller: App\Controller\EmployeeController::registerEmployee
register_succesfull:
    path: 'register_succesfull'
    controller: App\Controller\EmployeeController::registerSuccessfullNotificate
employee_save:
    path: 'employee_save'
    controller: App\Controller\EmployeeController::employeeSave