security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Employee
                property: email

    access_control:
        # 允许所有用户（包括匿名用户）访问 /profile 和 /search
        #- { path: ^/profile, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/search, roles: ROLE_WAREHOUSE_MANAGER }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator

            # 注销相关设置
            logout:
                path: app_logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 一周的有效时间
                path: /

    # Test environment specific security settings
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10