# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    default_locale: '%locale%'

    session:
        handler_id: null
        cookie_lifetime: 7200
        gc_maxlifetime: 7200
        cookie_secure: auto
        cookie_samesite: lax


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
