parameters:
    MAX_ARTICLES_COUNT_PER_PAGE: '%env(MAX_ARTICLES_COUNT_PER_PAGE)%'
    NAME_MAX_LENGTH: '%env(NAME_MAX_LENGTH)%'
    CONTENT_MAX_LENGTH: '%env(CONTENT_MAX_LENGTH)%'
    images_directory: '%kernel.project_dir%/public/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\BaseController:
        arguments:
            $twig: '@twig'
            $logger: '@logger'

    App\Twig\LocalizedPathExtension:
        tags: ['twig.extension']