<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241216142737 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE customer_id_seq CASCADE');
        $this->addSql('DROP TABLE product_document_vector');
        $this->addSql('DROP TABLE customer');
        $this->addSql('ALTER TABLE category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('DROP INDEX employee_email_key');
        $this->addSql('ALTER TABLE employee ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE employee ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D9F75A1E7769B0F ON employee (surname)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D9F75A15E237E06 ON employee (name)');
        $this->addSql('ALTER TABLE product ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product ALTER description TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE product ALTER price SET NOT NULL');
        $this->addSql('ALTER TABLE product ALTER discount DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER currency SET NOT NULL');
        $this->addSql('ALTER TABLE shop_info ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE shop_info ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SEQUENCE customer_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE product_document_vector (id INT NOT NULL, document TEXT DEFAULT NULL, vector TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE customer (id INT DEFAULT customer_id_seq NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, is_verified BOOLEAN DEFAULT false, reset_token VARCHAR(255) DEFAULT NULL, reset_token_expiration TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, wishlist JSON DEFAULT \'[]\', PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX customer_email_key ON customer (email)');
        $this->addSql('DROP INDEX UNIQ_5D9F75A1E7769B0F');
        $this->addSql('DROP INDEX UNIQ_5D9F75A15E237E06');
        $this->addSql('ALTER TABLE employee ALTER id SET DEFAULT employee_id_seq');
        $this->addSql('ALTER TABLE employee ALTER id DROP IDENTITY');
        $this->addSql('CREATE UNIQUE INDEX employee_email_key ON employee (email)');
        $this->addSql('ALTER TABLE product ALTER id SET DEFAULT product_id_seq');
        $this->addSql('ALTER TABLE product ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE product ALTER description TYPE TEXT');
        $this->addSql('ALTER TABLE product ALTER price DROP NOT NULL');
        $this->addSql('ALTER TABLE product ALTER discount SET DEFAULT \'100\'');
        $this->addSql('ALTER TABLE product ALTER currency DROP NOT NULL');
        $this->addSql('ALTER TABLE category ALTER id SET DEFAULT category_id_seq');
        $this->addSql('ALTER TABLE category ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE shop_info ALTER id SET DEFAULT shop_info_id_seq');
        $this->addSql('ALTER TABLE shop_info ALTER id DROP IDENTITY');
    }
}
