<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260107010932 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ProductColor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, hex VARCHAR(7) DEFAULT \'#FFFFFF\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE Size (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57F28B545E237E06 ON Size (name)');
        $this->addSql('CREATE TABLE api_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, public_id VARCHAR(64) NOT NULL, secret_hash VARCHAR(255) NOT NULL, label VARCHAR(255) DEFAULT NULL, scopes JSON DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BA2F5EBB5B48B91 ON api_token (public_id)');
        $this->addSql('CREATE TABLE cart (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, added_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BA388B79395C3F3 ON cart (customer_id)');
        $this->addSql('CREATE INDEX IDX_BA388B74584665A ON cart (product_id)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE category_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, category_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3F2070412469DE2 ON category_translation (category_id)');
        $this->addSql('CREATE TABLE color_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, color_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C81038637ADA1FB5 ON color_translation (color_id)');
        $this->addSql('CREATE TABLE currency (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(3) NOT NULL, value DOUBLE PRECISION NOT NULL, is_default BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) DEFAULT NULL, password_hash VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_verified BOOLEAN NOT NULL, reset_token VARCHAR(255) DEFAULT NULL, reset_token_expiration TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, wishlist JSON DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE employee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, surname VARCHAR(180) NOT NULL, name VARCHAR(180) NOT NULL, roles jsonb, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone_number VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D9F75A1E7927C74 ON employee (email)');
        $this->addSql('CREATE TABLE order_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_name VARCHAR(255) NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, subtotal NUMERIC(10, 2) NOT NULL, sku VARCHAR(255) NOT NULL, order_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_62809DB08D9F6D38 ON order_items (order_id)');
        $this->addSql('CREATE INDEX IDX_62809DB04584665A ON order_items (product_id)');
        $this->addSql('CREATE TABLE orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_price NUMERIC(10, 2) NOT NULL, address TEXT NOT NULL, order_created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, pickup_or_delivery_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_completed BOOLEAN DEFAULT false NOT NULL, payment_status VARCHAR(50) DEFAULT \'PENDING\' NOT NULL, payment_method VARCHAR(50) DEFAULT NULL, delivery_status VARCHAR(50) DEFAULT \'PENDING\' NOT NULL, notes TEXT DEFAULT NULL, discount NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, delivery_method VARCHAR(20) DEFAULT \'pickup\' NOT NULL, customer_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E52FFDEE9395C3F3 ON orders (customer_id)');
        $this->addSql('CREATE TABLE payments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) DEFAULT \'CZK\' NOT NULL, status VARCHAR(20) DEFAULT \'PENDING\' NOT NULL, provider VARCHAR(32) DEFAULT \'mock\' NOT NULL, transaction_id VARCHAR(64) DEFAULT NULL, payload JSON DEFAULT NULL, currency_code VARCHAR(3) DEFAULT \'CZK\' NOT NULL, fx_rate NUMERIC(18, 8) DEFAULT \'1.00000000\' NOT NULL, amount_in_currency NUMERIC(12, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, order_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_65D29B328D9F6D38 ON payments (order_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, number_in_stock INT NOT NULL, image_urls JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, width DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, length DOUBLE PRECISION DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, material VARCHAR(255) DEFAULT NULL, price DOUBLE PRECISION NOT NULL, hidden BOOLEAN NOT NULL, discount DOUBLE PRECISION NOT NULL, attributes JSON DEFAULT NULL, version INT DEFAULT 1 NOT NULL, sku VARCHAR(255) DEFAULT \'UNKNOWN\' NOT NULL, tax_rate DOUBLE PRECISION NOT NULL, category_id INT DEFAULT NULL, size_id INT DEFAULT NULL, color_id INT DEFAULT NULL, currency_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD498DA827 ON product (size_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD7ADA1FB5 ON product (color_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD38248176 ON product (currency_id)');
        $this->addSql('CREATE TABLE product_document_vector (sku VARCHAR(255) NOT NULL, document TEXT DEFAULT NULL, vector TEXT DEFAULT NULL, PRIMARY KEY(sku))');
        $this->addSql('CREATE TABLE product_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, name TEXT DEFAULT NULL, description TEXT DEFAULT NULL, material VARCHAR(255) DEFAULT NULL, attributes JSON DEFAULT NULL, product_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1846DB704584665A ON product_translation (product_id)');
        $this->addSql('CREATE TABLE return_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_email VARCHAR(255) NOT NULL, user_phone VARCHAR(20) NOT NULL, user_name VARCHAR(100) NOT NULL, return_reason TEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'pending\' NOT NULL, user_message TEXT DEFAULT NULL, product_skus TEXT NOT NULL, request_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6DFF31068D9F6D38 ON return_requests (order_id)');
        $this->addSql('CREATE TABLE shipment_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_code VARCHAR(32) NOT NULL, description TEXT DEFAULT NULL, event_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, location VARCHAR(128) DEFAULT NULL, shipment_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F5B7CD8F7BE036FC ON shipment_events (shipment_id)');
        $this->addSql('CREATE TABLE shipments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, carrier VARCHAR(64) DEFAULT \'MockExpress\' NOT NULL, tracking_number VARCHAR(64) DEFAULT NULL, status VARCHAR(32) DEFAULT \'CREATED\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, order_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_94699AD43E1C9C18 ON shipments (tracking_number)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_94699AD48D9F6D38 ON shipments (order_id)');
        $this->addSql('CREATE TABLE shop_info (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, eshop_name VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, telephone VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, about_us TEXT DEFAULT NULL, how_to_order TEXT DEFAULT NULL, business_conditions TEXT DEFAULT NULL, privacy_policy TEXT DEFAULT NULL, shipping_info TEXT DEFAULT NULL, payment TEXT DEFAULT NULL, refund TEXT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, carousel_pictures JSON DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, cin VARCHAR(50) DEFAULT NULL, hide_prices BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE shop_info_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(10) NOT NULL, about_us TEXT DEFAULT NULL, how_to_order TEXT DEFAULT NULL, business_conditions TEXT DEFAULT NULL, privacy_policy TEXT DEFAULT NULL, shipping_info TEXT DEFAULT NULL, payment TEXT DEFAULT NULL, refund TEXT DEFAULT NULL, shop_info_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4A0C68215EB881D2 ON shop_info_translation (shop_info_id)');
        $this->addSql('CREATE TABLE trusted_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B79395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B74584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE category_translation ADD CONSTRAINT FK_3F2070412469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE color_translation ADD CONSTRAINT FK_C81038637ADA1FB5 FOREIGN KEY (color_id) REFERENCES ProductColor (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB08D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_items ADD CONSTRAINT FK_62809DB04584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B328D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD498DA827 FOREIGN KEY (size_id) REFERENCES Size (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD7ADA1FB5 FOREIGN KEY (color_id) REFERENCES ProductColor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD38248176 FOREIGN KEY (currency_id) REFERENCES currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_translation ADD CONSTRAINT FK_1846DB704584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE return_requests ADD CONSTRAINT FK_6DFF31068D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE shipment_events ADD CONSTRAINT FK_F5B7CD8F7BE036FC FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE shipments ADD CONSTRAINT FK_94699AD48D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE shop_info_translation ADD CONSTRAINT FK_4A0C68215EB881D2 FOREIGN KEY (shop_info_id) REFERENCES shop_info (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE cart DROP CONSTRAINT FK_BA388B79395C3F3');
        $this->addSql('ALTER TABLE cart DROP CONSTRAINT FK_BA388B74584665A');
        $this->addSql('ALTER TABLE category_translation DROP CONSTRAINT FK_3F2070412469DE2');
        $this->addSql('ALTER TABLE color_translation DROP CONSTRAINT FK_C81038637ADA1FB5');
        $this->addSql('ALTER TABLE order_items DROP CONSTRAINT FK_62809DB08D9F6D38');
        $this->addSql('ALTER TABLE order_items DROP CONSTRAINT FK_62809DB04584665A');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEE9395C3F3');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B328D9F6D38');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD498DA827');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD7ADA1FB5');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD38248176');
        $this->addSql('ALTER TABLE product_translation DROP CONSTRAINT FK_1846DB704584665A');
        $this->addSql('ALTER TABLE return_requests DROP CONSTRAINT FK_6DFF31068D9F6D38');
        $this->addSql('ALTER TABLE shipment_events DROP CONSTRAINT FK_F5B7CD8F7BE036FC');
        $this->addSql('ALTER TABLE shipments DROP CONSTRAINT FK_94699AD48D9F6D38');
        $this->addSql('ALTER TABLE shop_info_translation DROP CONSTRAINT FK_4A0C68215EB881D2');
        $this->addSql('DROP TABLE ProductColor');
        $this->addSql('DROP TABLE Size');
        $this->addSql('DROP TABLE api_token');
        $this->addSql('DROP TABLE cart');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE category_translation');
        $this->addSql('DROP TABLE color_translation');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE order_items');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_document_vector');
        $this->addSql('DROP TABLE product_translation');
        $this->addSql('DROP TABLE return_requests');
        $this->addSql('DROP TABLE shipment_events');
        $this->addSql('DROP TABLE shipments');
        $this->addSql('DROP TABLE shop_info');
        $this->addSql('DROP TABLE shop_info_translation');
        $this->addSql('DROP TABLE trusted_code');
    }
}
