\i DB/category.sql
\i DB/color.sql
\i DB/currency.sql
\i DB/size.sql
\i DB/customer.sql
\i DB/employee.sql
\i DB/product.sql
\i DB/cart.sql
\i DB/order.sql
\i DB/order_items.sql
\i DB/return_requests.sql
\i DB/shopInfo.sql
\i DB/admin_code.sql
\i DB/trusted_code.sql