# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'en'
    MAX_ARTICLES_COUNT_PER_PAGE: '%env(MAX_ARTICLES_COUNT_PER_PAGE)%'
    NAME_MAX_LENGTH: '%env(NAME_MAX_LENGTH)%'
    CONTENT_MAX_LENGTH: '%env(CONTENT_MAX_LENGTH)%'
    BMS_URL: '%env(BMS_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Twig\AppExtension:
        tags: [ 'twig.extension' ]
        public: true    # ✅ 关键点：确保它是公开服务
    App\EventSubscriber\LocaleSubscriber:
        arguments:
            $defaultLocale: '%locale%'
        tags:
            - { name: kernel.event_subscriber }
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    