parameters:
    locale: 'en'
    MAX_ARTICLES_COUNT_PER_PAGE: '%env(MAX_ARTICLES_COUNT_PER_PAGE)%'
    NAME_MAX_LENGTH: '%env(NAME_MAX_LENGTH)%'
    CONTENT_MAX_LENGTH: '%env(CONTENT_MAX_LENGTH)%'
    BMS_URL: '%env(string:BMS_URL)%'
    search_service_base_url: '%env(SEARCH_SERVICE_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $searchServiceBaseUrl: '%search_service_base_url%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Twig\LocalizedPathExtension:
        tags: ['twig.extension']
    App\Twig\MoneyExtension:
        arguments:
            $cm: '@App\Service\CurrencyManager'
        tags: ['twig.extension']

    App\Service\CurrencyManager:
        arguments:
            $doctrine: '@doctrine'
            $requestStack: '@request_stack'
            $logger: '@logger'

    App\EventSubscriber\LocaleSubscriber:
        arguments:
            $defaultLocale: '%locale%'
        tags:
            - { name: kernel.event_subscriber }

    App\EventSubscriber\GlobalVariableSubscriber:
        tags: ['kernel.event_subscriber']

    App\Controller\BaseController:
        arguments:
            $twig: '@twig'
            $logger: '@logger'
            $doctrine: '@doctrine'