CREATE TABLE Product (
    ID INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    kategory VARCHAR(255) DEFAULT NULL,
    description VARCHAR(255) DEFAULT NULL,
    NUMBER_IN_STOCK INT NOT NULL,
    image_url VARCHAR(255) DEFAULT NULL,
    add_time VARCHAR(255) NOT NULL,
    width DOUBLE DEFAULT NULL,
    height DOUBLE DEFAULT NULL,
    length DOUBLE DEFAULT NULL,
    weight DOUBLE DEFAULT NULL,
    material VARCHAR(255) DEFAULT NULL,
    color VARCHAR(255) DEFAULT NULL,
    price DOUBLE DEFAULT NULL,
    hidden TINYINT(1) NOT NULL,
    discount DOUBLE NOT NULL DEFAULT 100,
    PRIMARY KEY (ID)
);