CREATE TABLE Product (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    kategory VARCHAR(255) DEFAULT NULL,
    description VARCHAR(255) DEFAULT NULL,
    number_in_stock INT NOT NULL,
    image_url VARCHAR(255) DEFAULT NULL,
    add_time TIMESTAMP NOT NULL,
    width DOUBLE PRECISION DEFAULT NULL,
    height DOUBLE PRECISION DEFAULT NULL,
    length DOUBLE PRECISION DEFAULT NULL,
    weight DOUBLE PRECISION DEFAULT NULL,
    material VARCHAR(255) DEFAULT NULL,
    color VARCHAR(255) DEFAULT NULL,
    price DOUBLE PRECISION DEFAULT NULL,
    hidden BOOLEAN NOT NULL,
    discount DOUBLE PRECISION NOT NULL DEFAULT 100
);
