from database import get_connection


class SemanticVectorRepository:
    LATEST_INDEXABLE_PRODUCT_SUBQUERY = """
        SELECT
            sku,
            MAX(id) AS max_id
        FROM product
        WHERE sku IS NOT NULL
          AND sku <> ''
        GROUP BY sku
        HAVING COUNT(*) FILTER (
            WHERE hidden = true
        ) = 0
    """

    @staticmethod
    def apply_ivfflat_probes(
        cursor,
        ivfflat_probes: int,
    ) -> None:
        try:
            probes = int(ivfflat_probes)
        except (TypeError, ValueError):
            probes = 10

        if probes < 1:
            probes = 10

        cursor.execute(
            """
            SELECT set_config(
                'ivfflat.probes',
                %s,
                true
            )
            """,
            (str(probes),),
        )
    def ensure_table(
        self,
        embedding_dimension: int,
    ) -> None:
        try:
            embedding_dimension = int(
                embedding_dimension
            )
        except (TypeError, ValueError) as exc:
            raise ValueError(
                "Embedding dimension must be an integer."
            ) from exc

        if embedding_dimension < 1:
            raise ValueError(
                "Embedding dimension must be greater than zero."
            )

        sql_extension = """
            CREATE EXTENSION IF NOT EXISTS vector
        """

        sql_table = f"""
            CREATE TABLE IF NOT EXISTS product_semantic_vector (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                product_id INT NOT NULL,
                embedding vector({embedding_dimension}) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE
                    DEFAULT CURRENT_TIMESTAMP NOT NULL,

                PRIMARY KEY (id),

                CONSTRAINT uniq_product_semantic_vector_product_id
                    UNIQUE (product_id)
            )
        """

        sql_foreign_key = """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname =
                        'fk_product_semantic_vector_product_id'
                ) THEN
                    ALTER TABLE product_semantic_vector
                    ADD CONSTRAINT
                        fk_product_semantic_vector_product_id
                    FOREIGN KEY (product_id)
                    REFERENCES product (id)
                    ON DELETE CASCADE;
                END IF;
            END
            $$;
        """

        sql_product_index = """
            CREATE INDEX IF NOT EXISTS
                idx_product_semantic_vector_product_id
            ON product_semantic_vector (product_id)
        """

        sql_embedding_index = """
            CREATE INDEX IF NOT EXISTS
                idx_product_semantic_vector_embedding
            ON product_semantic_vector
            USING ivfflat (
                embedding vector_cosine_ops
            )
            WITH (lists = 100)
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(sql_extension)
                cursor.execute(sql_table)
                cursor.execute(sql_foreign_key)
                cursor.execute(sql_product_index)
                cursor.execute(sql_embedding_index)

            conn.commit()

    def get_products_for_indexing(
        self,
    ) -> list[dict]:
        """
        Returns the newest product row for every SKU
        that has no hidden version.
        """

        sql = f"""
            SELECT
                p.id,
                p.name,
                p.description,
                p.material,
                p.attributes,
                p.width,
                p.height,
                p.length,
                p.weight,
                p.price,
                p.sku,

                c.name AS category_name,
                pc.name AS color_name,
                s.name AS size_name

            FROM product p

            INNER JOIN (
                {self.LATEST_INDEXABLE_PRODUCT_SUBQUERY}
            ) latest
                ON latest.max_id = p.id

            LEFT JOIN category c
                ON c.id = p.category_id

            LEFT JOIN productcolor pc
                ON pc.id = p.color_id

            LEFT JOIN size s
                ON s.id = p.size_id

            ORDER BY p.id DESC
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(sql)

                return cursor.fetchall()

    def get_product_for_indexing_by_sku(
        self,
        sku: str,
    ) -> dict | None:
        sku = str(
            sku or ""
        ).strip()

        if not sku:
            return None

        sql = """
            SELECT
                p.id,
                p.name,
                p.description,
                p.material,
                p.attributes,
                p.width,
                p.height,
                p.length,
                p.weight,
                p.price,
                p.sku,

                c.name AS category_name,
                pc.name AS color_name,
                s.name AS size_name

            FROM product p

            LEFT JOIN category c
                ON c.id = p.category_id

            LEFT JOIN productcolor pc
                ON pc.id = p.color_id

            LEFT JOIN size s
                ON s.id = p.size_id

            WHERE p.sku = %s

            AND NOT EXISTS (
                SELECT 1
                FROM product hidden_version
                WHERE hidden_version.sku = p.sku
                    AND hidden_version.hidden = true
            )

            ORDER BY p.id DESC
            LIMIT 1
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    sql,
                    (sku,),
                )

                return cursor.fetchone()

    def save_embedding(
        self,
        product_id: int,
        embedding: str,
    ) -> None:
        sql = """
            INSERT INTO product_semantic_vector (
                product_id,
                embedding,
                updated_at
            )
            VALUES (
                %s,
                %s::vector,
                NOW()
            )

            ON CONFLICT (product_id)
            DO UPDATE SET
                embedding = EXCLUDED.embedding,
                updated_at = NOW()
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    sql,
                    (
                        product_id,
                        embedding,
                    ),
                )

            conn.commit()

    def delete_embedding_by_product_id(
        self,
        product_id: int,
    ) -> int:
        if product_id is None:
            return 0

        sql = """
            DELETE FROM product_semantic_vector
            WHERE product_id = %s
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    sql,
                    (product_id,),
                )

                deleted = cursor.rowcount

            conn.commit()

        return int(deleted)

    def delete_embedding_by_sku(
        self,
        sku: str,
    ) -> int:
        sku = str(
            sku or ""
        ).strip()

        if not sku:
            return 0

        sql = """
            DELETE FROM product_semantic_vector vector_row

            USING product product_row

            WHERE vector_row.product_id = product_row.id
              AND product_row.sku = %s
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    sql,
                    (sku,),
                )

                deleted = cursor.rowcount

            conn.commit()

        return int(deleted)

    def delete_all_embeddings(
        self,
    ) -> int:
        """
        Can be used before a complete semantic reindex.
        """

        sql = """
            DELETE FROM product_semantic_vector
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(sql)
                deleted = cursor.rowcount

            conn.commit()

        return int(deleted)

    def search_by_vector(
        self,
        query_vector: str,
        limit: int,
        ivfflat_probes: int = 10,
    ) -> list[dict]:
        limit = max(
            1,
            int(limit),
        )

        sql = f"""
            SELECT
                p.id,
                p.name,
                p.description,
                p.price,
                p.sku,
                p.material,
                p.attributes,

                c.name AS category_name,
                pc.name AS color_name,
                s.name AS size_name,

                1 - (
                    vector_row.embedding
                    <=> %s::vector
                ) AS similarity

            FROM product_semantic_vector vector_row

            JOIN product p
                ON p.id = vector_row.product_id

            INNER JOIN (
                {self.LATEST_INDEXABLE_PRODUCT_SUBQUERY}
            ) latest
                ON latest.max_id = p.id

            LEFT JOIN category c
                ON c.id = p.category_id

            LEFT JOIN productcolor pc
                ON pc.id = p.color_id

            LEFT JOIN size s
                ON s.id = p.size_id

            ORDER BY
                vector_row.embedding
                <=> %s::vector

            LIMIT %s
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                self.apply_ivfflat_probes(
                    cursor,
                    ivfflat_probes,
                )

                cursor.execute(
                    sql,
                    (
                        query_vector,
                        query_vector,
                        limit,
                    ),
                )

                return cursor.fetchall()

    def get_product_vector(
        self,
        product_id: int,
    ) -> str | None:
        sql = f"""
            SELECT
                vector_row.embedding::text AS embedding

            FROM product_semantic_vector vector_row

            JOIN product product_row
                ON product_row.id =
                vector_row.product_id

            INNER JOIN (
                {self.LATEST_INDEXABLE_PRODUCT_SUBQUERY}
            ) latest
                ON latest.max_id =
                product_row.id

            WHERE vector_row.product_id = %s
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    sql,
                    (product_id,),
                )

                row = cursor.fetchone()

        if row is None:
            return None

        if isinstance(row, dict):
            return row.get("embedding")

        return row[0]

    def find_similar_products(
        self,
        product_id: int,
        product_vector: str,
        limit: int,
        ivfflat_probes: int = 10,
    ) -> list[dict]:
        limit = max(
            1,
            int(limit),
        )

        sql = f"""
            SELECT
                p.id,
                p.name,
                p.description,
                p.price,
                p.sku,
                p.material,
                p.attributes,

                c.name AS category_name,
                pc.name AS color_name,
                s.name AS size_name,

                1 - (
                    vector_row.embedding
                    <=> %s::vector
                ) AS similarity

            FROM product_semantic_vector vector_row

            JOIN product p
                ON p.id = vector_row.product_id

            INNER JOIN (
                {self.LATEST_INDEXABLE_PRODUCT_SUBQUERY}
            ) latest
                ON latest.max_id = p.id

            LEFT JOIN category c
                ON c.id = p.category_id

            LEFT JOIN productcolor pc
                ON pc.id = p.color_id

            LEFT JOIN size s
                ON s.id = p.size_id

            WHERE p.id <> %s

            ORDER BY
                vector_row.embedding
                <=> %s::vector

            LIMIT %s
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                self.apply_ivfflat_probes(
                    cursor,
                    ivfflat_probes,
                )

                cursor.execute(
                    sql,
                    (
                        product_vector,
                        product_id,
                        product_vector,
                        limit,
                    ),
                )

                return cursor.fetchall()

    def get_latest_product_id_by_sku(
        self,
        sku: str,
    ) -> int | None:
        sku = str(
            sku or ""
        ).strip()

        if not sku:
            return None

        sql = """
            SELECT p.id

            FROM product p

            WHERE p.sku = %s

            AND NOT EXISTS (
                SELECT 1
                FROM product hidden_version
                WHERE hidden_version.sku = p.sku
                    AND hidden_version.hidden = true
            )

            ORDER BY p.id DESC
            LIMIT 1
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    sql,
                    (sku,),
                )

                row = cursor.fetchone()

        if row is None:
            return None

        if isinstance(row, dict):
            product_id = row.get("id")
        else:
            product_id = row[0]

        return (
            int(product_id)
            if product_id is not None
            else None
        )

    def count_semantic_vectors(
        self,
    ) -> int:
        sql_table_exists = """
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = current_schema()
                  AND table_name =
                      'product_semantic_vector'
            ) AS table_exists
        """

        sql_count = """
            SELECT COUNT(*) AS count
            FROM product_semantic_vector
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    sql_table_exists
                )

                row = cursor.fetchone()

                if isinstance(row, dict):
                    table_exists = bool(
                        row.get("table_exists")
                    )
                else:
                    table_exists = bool(
                        row[0]
                    )

                if not table_exists:
                    return 0

                cursor.execute(sql_count)
                row = cursor.fetchone()

        if isinstance(row, dict):
            return int(
                row.get("count", 0)
            )

        return int(row[0])

    def has_product_vector_by_sku(
        self,
        sku: str,
    ) -> bool:
        sku = str(
            sku or ""
        ).strip()

        if not sku:
            return False

        sql = f"""
            SELECT EXISTS (
                SELECT 1

                FROM product_semantic_vector vector_row

                JOIN product product_row
                    ON product_row.id =
                    vector_row.product_id

                INNER JOIN (
                    {self.LATEST_INDEXABLE_PRODUCT_SUBQUERY}
                ) latest
                    ON latest.max_id =
                    product_row.id

                WHERE product_row.sku = %s
            ) AS vector_exists
        """

        try:
            with get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(
                        sql,
                        (sku,),
                    )

                    row = cursor.fetchone()

            if isinstance(row, dict):
                return bool(
                    row.get("vector_exists")
                )

            return bool(row[0])

        except Exception:
            return False
        
    def delete_embeddings_except_product_ids(
        self,
        product_ids: list[int],
    ) -> int:
        normalized_ids = [
            int(product_id)
            for product_id in product_ids
            if product_id is not None
        ]

        if not normalized_ids:
            return self.delete_all_embeddings()

        sql = """
            DELETE FROM product_semantic_vector
            WHERE NOT (
                product_id = ANY(%s)
            )
        """

        with get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    sql,
                    (normalized_ids,),
                )

                deleted = cursor.rowcount

            conn.commit()

        return int(deleted)