from database import get_connection


class SemanticVectorRepository:
    def ensure_table(self, embedding_dimension: int):
        sql_extension = """
            CREATE EXTENSION IF NOT EXISTS vector
        """

        sql_table = f"""
            CREATE TABLE IF NOT EXISTS product_semantic_vector (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                product_id INT NOT NULL,
                embedding vector({embedding_dimension}) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                PRIMARY KEY (id),
                CONSTRAINT uniq_product_semantic_vector_product_id UNIQUE (product_id)
            )
        """

        sql_foreign_key = """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'fk_product_semantic_vector_product_id'
                ) THEN
                    ALTER TABLE product_semantic_vector
                    ADD CONSTRAINT fk_product_semantic_vector_product_id
                    FOREIGN KEY (product_id)
                    REFERENCES product (id)
                    ON DELETE CASCADE;
                END IF;
            END
            $$;
        """

        sql_product_index = """
            CREATE INDEX IF NOT EXISTS idx_product_semantic_vector_product_id
            ON product_semantic_vector (product_id)
        """

        sql_embedding_index = """
            CREATE INDEX IF NOT EXISTS idx_product_semantic_vector_embedding
            ON product_semantic_vector
            USING ivfflat (embedding vector_cosine_ops)
            WITH (lists = 100)
        """

        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql_extension)
                cur.execute(sql_table)
                cur.execute(sql_foreign_key)
                cur.execute(sql_product_index)
                cur.execute(sql_embedding_index)

            conn.commit()

    def get_products_for_indexing(self):
        sql = """
            SELECT
                p.id,
                p.name,
                p.description,
                p.material,
                p.width,
                p.height,
                p.length,
                p.weight,
                p.price,
                p.sku,
                c.name AS category_name,
                pc.name AS color_name,
                s.name AS size_name
            FROM product p
            LEFT JOIN category c ON c.id = p.category_id
            LEFT JOIN productcolor pc ON pc.id = p.color_id
            LEFT JOIN size s ON s.id = p.size_id
            WHERE p.hidden = false
        """

        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql)
                return cur.fetchall()

    def save_embedding(self, product_id: int, embedding: str):
        sql = """
            INSERT INTO product_semantic_vector
                (product_id, embedding, updated_at)
            VALUES
                (%s, %s::vector, NOW())
            ON CONFLICT (product_id)
            DO UPDATE SET
                embedding = EXCLUDED.embedding,
                updated_at = NOW()
        """

        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, (product_id, embedding))

            conn.commit()

    def search_by_vector(self, query_vector: str, limit: int):
        sql = """
            SELECT
                p.id,
                p.name,
                p.description,
                p.price,
                p.sku,
                p.material,
                c.name AS category_name,
                pc.name AS color_name,
                s.name AS size_name,
                1 - (v.embedding <=> %s::vector) AS similarity
            FROM product_semantic_vector v
            JOIN product p ON p.id = v.product_id
            LEFT JOIN category c ON c.id = p.category_id
            LEFT JOIN productcolor pc ON pc.id = p.color_id
            LEFT JOIN size s ON s.id = p.size_id
            WHERE p.hidden = false
            ORDER BY v.embedding <=> %s::vector
            LIMIT %s
        """

        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, (query_vector, query_vector, limit))
                return cur.fetchall()

    def get_product_vector(self, product_id: int):
        sql = """
            SELECT embedding::text AS embedding
            FROM product_semantic_vector
            WHERE product_id = %s
        """

        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, (product_id,))
                row = cur.fetchone()

        if row is None:
            return None

        return row["embedding"] if isinstance(row, dict) else row[0]

    def find_similar_products(self, product_id: int, product_vector: str, limit: int):
        sql = """
            SELECT
                p.id,
                p.name,
                p.description,
                p.price,
                p.sku,
                p.material,
                c.name AS category_name,
                pc.name AS color_name,
                s.name AS size_name,
                1 - (v.embedding <=> %s::vector) AS similarity
            FROM product_semantic_vector v
            JOIN product p ON p.id = v.product_id
            LEFT JOIN category c ON c.id = p.category_id
            LEFT JOIN productcolor pc ON pc.id = p.color_id
            LEFT JOIN size s ON s.id = p.size_id
            WHERE p.hidden = false
              AND p.id <> %s
            ORDER BY v.embedding <=> %s::vector
            LIMIT %s
        """

        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    sql,
                    (
                        product_vector,
                        product_id,
                        product_vector,
                        limit,
                    ),
                )
                return cur.fetchall()
            

    def get_latest_product_id_by_sku(self, sku: str):
        sql = """
            SELECT id
            FROM product
            WHERE sku = %s
            AND hidden = false
            ORDER BY id DESC
            LIMIT 1
        """

        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, (sku,))
                row = cur.fetchone()

        if row is None:
            return None

        return row["id"] if isinstance(row, dict) else row[0]
    
    def count_semantic_vectors(self) -> int:
        sql_table_exists = """
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = 'product_semantic_vector'
            ) AS exists
        """

        sql_count = """
            SELECT COUNT(*) AS cnt
            FROM product_semantic_vector
        """

        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql_table_exists)
                row = cur.fetchone()

                exists = bool(row["exists"]) if isinstance(row, dict) else bool(row[0])

                if not exists:
                    return 0

                cur.execute(sql_count)
                row = cur.fetchone()

        return int(row["cnt"] if isinstance(row, dict) else row[0])


    def has_product_vector_by_sku(self, sku: str) -> bool:
        sql = """
            SELECT COUNT(*) AS cnt
            FROM product_semantic_vector v
            JOIN product p ON p.id = v.product_id
            WHERE p.sku = %s
            AND p.hidden = false
        """

        try:
            with get_connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(sql, (sku,))
                    row = cur.fetchone()

            return int(row["cnt"] if isinstance(row, dict) else row[0]) > 0
        except Exception:
            return False